package anydesk

import (
	"bytes"
	"crypto/hmac"
	"crypto/sha1"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

const (
	// Used by various calls to indicate unlimited results/items
	Infinite = int64(-1)
)

// ApiRequest is the basic interface used for all compatible API requests.
type ApiRequest interface {
	// Returns debug information
	GetDebug() *DebugInfo

	// Returns base information about the http request. This information
	// is used to compose the API request signature.
	GetRequestDetails() *BaseRequest

	// Returns the http.Request that is composed, signed and ready to execute
	GetHttpRequest(api *Api) (req *http.Request, err error)
}

type PaginatedApiRequest interface {
	ApiRequest

	// Returns the pagination options for the current request
	GetPaginationOptions() *PaginationOptions
}

// Api contains all information about the AnyDesk API endpoint and configurable options.
type Api struct {
	// API license ID as provided by AnyDesk support
	LicenseId string `json:"license_id"`

	// API password as provided by AnyDesk support
	ApiPassword string `json:"api_password"`

	// API endpoint to be used
	ApiEndpoint string `json:"api_endpoint"`

	// The http client used for API requests.
	// Can be used or overwritten for timeout and transport layer configuration.
	HttpClient *http.Client
}

// NewApi returns an initialized AnyDesk API configuration used with a Professional license.
func NewApi(licenseId string, apiPassword string) *Api {
	return &Api{
		LicenseId:   licenseId,
		ApiPassword: apiPassword,
		ApiEndpoint: "https://v1.api.anydesk.com:8081",
		HttpClient:  &http.Client{},
	}
}

// GetRequestToken generates the request token used for the API request.
func (api *Api) GetRequestToken(request *BaseRequest) string {
	h := hmac.New(sha1.New, []byte(api.ApiPassword))
	h.Write([]byte(request.GetRequestString()))

	return base64.StdEncoding.EncodeToString(h.Sum(nil))
}

// Do will execute a given AnyDesk API request and return the plain json as string.
func (api *Api) Do(request ApiRequest) (body []byte, err error) {
	base := request.GetRequestDetails()

	// Check if the request supports the

	// Ensure we encode the optional query parameters into the BaseRequest.Resource
	// otherwise the signature will not match
	if base.Query != nil {
		base.Resource = fmt.Sprintf("%s?%s", base.Resource, base.Query.Encode())
	}

	// Ensure we encode possible request content into json
	content, err := json.Marshal(request)
	if err != nil {
		return
	}

	base.Content = content

	// Collect request body for debug
	if isDebug {
		d := request.GetDebug()
		d.Available = true
		d.RequestBody = content
	}

	// Create a clean request
	r, err := request.GetHttpRequest(api)
	if err != nil {
		return
	}

	// Collect http request for debug
	if isDebug {
		d := request.GetDebug()
		d.Request = r
		d.RequestUrl = r.URL
	}

	resp, err := api.HttpClient.Do(r)

	if err != nil {
		return
	}

	// Collect http response for debug
	if isDebug {
		d := request.GetDebug()
		d.Response = resp
	}

	body, err = ioutil.ReadAll(resp.Body)
	if err != nil {
		return
	}

	// Collect response body for debug
	if isDebug {
		d := request.GetDebug()
		d.ResponseBody = body
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		err = errors.New(resp.Status)
		return
	}

	return
}

func (api *Api) DoPaginated(request PaginatedApiRequest) (body []byte, err error) {
	// Copy the pagination into the base query details
	p := request.GetPaginationOptions()
	base := request.GetRequestDetails()

	// Ensure the query parameters are available
	if base.Query == nil {
		base.Query = &url.Values{}
	}

	base.Query.Set("offset", strconv.FormatInt(p.Offset, 10))
	base.Query.Set("limit", strconv.FormatInt(p.Limit, 10))

	if p.Sort != "" {
		base.Query.Set("sort", p.Sort)
	}

	if p.Order != "" {
		base.Query.Set("order", string(p.Order))
	}

	return api.Do(request)
}

// BaseRequest contains the base information required to work against the API.
type BaseRequest struct {
	Method    string      `json:"-"`
	Resource  string      `json:"-"`
	Query     *url.Values `json:"-"`
	Timestamp int64       `json:"-"`
	Content   []byte      `json:"-"`

	debug *DebugInfo
}

// GetRequestDetails will return the base request details.
// Required by the ApiRequest interface.
func (r *BaseRequest) GetRequestDetails() *BaseRequest {
	return r
}

// GetContentHash generates the content hash required for the API request string generated by GetRequestString().
func (r *BaseRequest) GetContentHash() string {
	h := sha1.New()
	h.Write(r.Content)

	return base64.StdEncoding.EncodeToString(h.Sum(nil))
}

// GetRequestString generates the request string required for the API token generated by GetRequestToken().
func (r *BaseRequest) GetRequestString() string {
	return fmt.Sprintf("%s\n%s\n%d\n%s", strings.ToUpper(r.Method), r.Resource, r.Timestamp, r.GetContentHash())
}

// GetHttpRequest will return the prepared HTTP request that can be used by a http.Client
func (r *BaseRequest) GetHttpRequest(api *Api) (req *http.Request, err error) {
	endpoint := fmt.Sprintf("%s%s", api.ApiEndpoint, r.Resource)

	req, err = http.NewRequest(r.Method, endpoint, bytes.NewBuffer(r.Content))
	if err != nil {
		return
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("AD %s:%d:%s", api.LicenseId, r.Timestamp, api.GetRequestToken(r)))

	return
}
